version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '09:00'
      timezone: 'Etc/UTC'
    versioning-strategy: 'lockfile-only'
    open-pull-requests-limit: 10
