name: Danger

on:
  pull_request:
    branches:
    - '**'
  issue_comment:
    types:
    - created

jobs:
  danger-for-internal:
    name: Danger for internal - node.js 12.x
    if: |
      github.event_name == 'pull_request'
      && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
    - name: Clone the source for the event
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Danger JS
      run: npx danger ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  danger-for-external:
    name: Danger for external - node.js 12.x
    if: |
      github.event_name == 'issue_comment' && github.event.action == 'created'
      && github.event.issue.pull_request != null
      && startsWith(github.event.comment.body, '/danger')
    runs-on: ubuntu-latest
    steps:
    - name: Check repository permission for user
      uses: sushichop/action-repository-permission@v1
      with:
        required-permission: write
        reaction-permitted: rocket
    - name: Clone the PR source
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{ github.event.issue.number }}/head
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Danger JS
      run: npx danger ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
